# Generated by Django 4.2.4 on 2023-08-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_price_adj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="close",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="price",
            name="high",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="price",
            name="low",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="price",
            name="open",
            field=models.FloatField(),
        ),
    ]
