# Generated by Django 4.2.4 on 2023-09-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_price_close_alter_price_high_alter_price_low_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=40)),
                ("code", models.CharField(default="", max_length=40)),
                ("sector", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="price",
            name="code",
        ),
        migrations.AddField(
            model_name="price",
            name="stock",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app.stock"
            ),
            preserve_default=False,
        ),
    ]
